# version: '3.8'

# services:
#   backend:
#     build:
#       context: .
#       dockerfile: backend.Dockerfile
#     ports:
#       - "8000:8000"
#     environment:
#       - PYTHONUNBUFFERED=1
#     command: python core_api.py
#     networks:
#       - custom_network

#   frontend:
#     build:
#       context: .
#       dockerfile: frontend.Dockerfile
#     ports:
#       - "3000:3000"
#     environment:
#       - REACT_APP_BACKEND_URL=http://backend:8000
#     networks:
#       - custom_network

# networks:
#   custom_network:

version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    command: python core_api.py
    network_mode: "host"

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
    network_mode: "host"