import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";
import SideBarLayout from "./sideBarLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Bürokratt Prototype V1",
  description: "Generated by Rootcode AI",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className} suppressHydrationWarning={true}>
        <SideBarLayout children={children} />
      </body>
    </html>
  );
}
