"use client";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Prototype V1",
  description: "Generated by Rootcode AI",
};

export default function SideBarLayout({ children }) {
  // Mobile sidebar visibility state
  const [showSidebar, setShowSidebar] = useState(false);

  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className} suppressHydrationWarning={true}>
        <div className="min-h-screen">
          <div className="flex">
            <Sidebar show={showSidebar} setter={setShowSidebar} />
            <div className="flex flex-col flex-grow w-screen md:w-full min-h-screen">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
